# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: prometheus-grafana
#   namespace: argocd
# spec:
#   project: default
#   source:
#     chart: kube-prometheus-stack  # This is the official Helm chart for Prometheus + Grafana
#     repoURL: https://prometheus-community.github.io/helm-charts
#     targetRevision: 51.2.0  # Change this to the latest chart version
#     # targetRevision: main  # Change this to the latest chart version
#     helm:
#       values: |
#         grafana:
#           adminPassword: "admin123"
#           service:
#             type: ClusterIP
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: monitoring  # This namespace will be created automatically
#   syncPolicy:
#     automated:
#       prune: true
#       selfHeal: true
#     syncOptions:
#       - CreateNamespace=true
